
public class Homework09 {

    // ToDo 01:  Write an algorithm to solve the following problem
    /*
    The sequence of triangle numbers is generated by adding the natural numbers. 
    So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
    The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over one hundred divisors?
    
     */
    public static void main(String[] args) {
        int num = 0;
        int triNum = 0;
        int count = 0;

        while (num <= 100) {
            num = 0;
            count++;
            triNum += count;

            for (int counter = 1; counter <= Math.sqrt(triNum); counter++) {
                if (triNum % counter == 0) {
                    num += 2;
                }
                if (Math.sqrt(triNum) * Math.sqrt(triNum) == triNum) {
                    num--;
                }
            }

        }
        System.out.println("The first triangle number over 100 divisors is " + triNum);
        // The first triangle number over 100 divisors is 73920
    }

}
